# Generated by Django 4.1.4 on 2023-02-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='users',
            new_name='user',
        ),
    ]
