# Generated by Django 4.1.4 on 2023-02-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_users_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
    ]
