# Generated by Django 4.1.4 on 2023-01-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tag_room_created_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, to='base.tag'),
        ),
    ]
