# Generated by Django 4.1.4 on 2023-02-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=''),
        ),
    ]
