# Generated by Django 4.1.4 on 2023-04-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_room_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-vote_ratio', '-vote_total', 'name']},
        ),
    ]
